local ADDON_NAME, SkillWeaver = ...
-- This file is automatically generated by scraper/interrupt_scraper.py
-- Run the scraper to populate this file with interrupt priorities.

SkillWeaver.Interrupts = SkillWeaver.Interrupts or {}
